<?php

declare(strict_types=1);

namespace ClearlyIP\MagoLsp;

use Composer\Composer;
use Composer\IO\IOInterface;
use Composer\Plugin\PluginInterface;

use function file_get_contents;
use function is_file;
use function is_link;
use function str_contains;
use function unlink;

use const DIRECTORY_SEPARATOR;
use const PHP_OS_FAMILY;

final class Plugin implements PluginInterface
{
    /**
     * Removes legacy files placed directly in the Composer bin-dir by plugin versions prior to
     * the addition of "bin": ["plugin/bin/mago-lsp"] in composer.json.
     *
     * Older versions used a POST_INSTALL_CMD handler to download and write the real mago-lsp
     * binary directly into vendor/bin/. Because those installs recorded no "bin" entry in the
     * lockfile, Composer's removeBinaries() is a no-op when upgrading, leaving the old file in
     * place. Composer then refuses to create the new PHP-proxy symlink and emits:
     *   "Skipped installation of bin …: name conflicts with an existing file"
     *
     * We clean up here — in activate() — so the slot is clear before Composer processes bins.
     * Composer-managed proxy files (recognised by their "Proxy PHP file generated by Composer"
     * header) are left untouched; only hand-placed real binaries are removed.
     */
    public function activate(Composer $composer, IOInterface $io): void
    {
        $binDir = (string) $composer->getConfig()->get('bin-dir');
        $ext    = PHP_OS_FAMILY === 'Windows' ? '.exe' : '';

        $binPath = $binDir . DIRECTORY_SEPARATOR . 'mago-lsp' . $ext;
        if (is_file($binPath) && !is_link($binPath)) {
            $contents = file_get_contents($binPath) ?: '';
            if (!str_contains($contents, 'Proxy PHP file generated by Composer')) {
                unlink($binPath);

                $versionSentinel = $binDir . DIRECTORY_SEPARATOR . '.mago-lsp-version';
                if (is_file($versionSentinel)) {
                    unlink($versionSentinel);
                }
            }
        }
    }

    public function deactivate(Composer $composer, IOInterface $io): void {}

    /**
     * Removes any legacy binary that older plugin versions placed directly in the Composer bin-dir.
     *
     * Newer installs use a PHP launcher script (plugin/bin/mago-lsp) that Composer manages
     * as a normal bin entry, so no manual cleanup is needed for those.
     */
    public function uninstall(Composer $composer, IOInterface $io): void
    {
        $binDir = (string) $composer->getConfig()->get('bin-dir');
        $ext    = PHP_OS_FAMILY === 'Windows' ? '.exe' : '';

        foreach (['mago-lsp' . $ext, '.mago-lsp-version'] as $file) {
            $path = $binDir . DIRECTORY_SEPARATOR . $file;
            if (is_file($path) && !is_link($path)) {
                unlink($path);
            }
        }
    }
}
